# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build: ./infra/nodemon
    volumes:
      - .:/usr/src/app
    restart: always
    ports:
      - 3000:80
    environment:
      MAPQUEST_API_KEY: ${MAPQUEST_API_KEY}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_DB: ${MONGO_DB}
  mongo:
    image: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - "./infra/mongodata:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
